import type { Metadata } from "next"
import { LegalPage, LegalTable } from "@/components/legal-page"

export const metadata: Metadata = { title: "Privacy Policy — Lumen" }

// Draft: the [bracketed] parts are still to be confirmed, and an attorney should review it before launch.
export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy Policy" effective="[EFFECTIVE DATE]">
      <h2>1. Who we are</h2>
      <p>
        [LEGAL ENTITY NAME] (&quot;Lumen&quot;, &quot;we&quot;) runs the Lumen course platform and is responsible for the personal data
        described here. Contact us at [PRIVACY EMAIL].
      </p>

      <h2>2. What we collect</h2>
      <LegalTable
        head={["Data", "Where it comes from", "When"]}
        rows={[
          ["Name, email address, profile picture", "Google or GitHub, when you sign in", "Every account"],
          ["Account ID and sign-in session", "Created by our sign-in system", "Every account"],
          ["Lesson progress: where you stopped, which lessons you completed", "Our video player, while you watch signed in", "Signed-in viewers"],
          ["Discussion posts (questions and replies)", "You", "When you post"],
          ["AI tutor messages and answers", "You and our AI provider", "When you use the tutor"],
          ["Daily count of AI answers", "Generated by us", "When you use the tutor"],
          ["Purchase and subscription records: order ID, product, status, renewal date", "Polar, our payment provider", "When you buy"],
          [
            "Technical and usage data: errors, performance traces, session replays, browser and device details, pages visited",
            "Your browser and our servers, through Sentry",
            "Any visit, including signed out",
          ],
        ]}
      />
      <p>We don&apos;t receive your card or bank details. Polar collects them directly at checkout.</p>
      <p>We don&apos;t use advertising trackers or third-party analytics.</p>

      <h2>3. How we use it</h2>
      <LegalTable
        head={["Purpose", "Data used", "Legal basis (EU/UK)"]}
        rows={[
          ["Run your account and give you the courses you bought", "Account, purchase records", "Contract"],
          ["Save your place and show your progress", "Lesson progress", "Contract"],
          ["Show discussions, with your name and picture beside your posts", "Posts, name, picture", "Contract"],
          ["Answer tutor questions and enforce the daily AI limit", "Tutor messages, AI answer count", "Contract"],
          ["Take payments and keep billing records", "Name, email, account ID, purchase records", "Contract; legal obligation"],
          ["Find and fix errors, and prevent abuse", "Technical and usage data", "Legitimate interests"],
        ]}
      />
      <p>
        We don&apos;t sell your personal data, use it for advertising, or make automated decisions about you that have legal or similar
        effects.
      </p>

      <h2>4. Who receives it</h2>
      <p>
        We share data only with the providers below, which process it on our behalf or, for sign-in and payments, as independent services
        under their own terms.
      </p>
      <LegalTable
        head={["Provider", "What they receive", "Why"]}
        rows={[
          ["Google, GitHub", "The sign-in request; they send us your name, email and picture", "Sign-in"],
          ["Neon", "Everything stored in our database, and sign-in sessions", "Database and authentication"],
          ["Polar", "Name, email and account ID at checkout, plus your payment details, which you enter directly", "Payments, tax, receipts, subscriptions"],
          [
            "OpenAI",
            "Your tutor messages, lesson notes, the course outline and which lessons you completed; for “Ask AI”, the question's text",
            "Generating tutor answers",
          ],
          ["Sentry", "Technical and usage data, session replays, and tutor messages and answers, tagged with your account ID", "Error monitoring and debugging"],
          ["ImageKit", "Requests for course videos and images, including your IP address", "Video and image delivery"],
          ["[HOSTING PROVIDER]", "Every request to the site", "Hosting"],
        ]}
      />
      <p>
        <strong>Other people on Lumen.</strong> Your discussion posts, name and picture are visible to anyone who can watch that lesson.
        For free preview lessons, that includes visitors who aren&apos;t signed in.
      </p>
      <p>We may also disclose data when the law requires it, or to a buyer if Lumen is sold or merged.</p>

      <h2>5. Error monitoring and session replay</h2>
      <p>
        We use Sentry to find and fix problems. Browser data is sent through our own site first, and from there to Sentry&apos;s EU data
        center.
      </p>
      <ul>
        <li>
          <strong>Session replay.</strong> Sentry records a replay of about 10% of visits, and of every visit where an error occurs. A
          replay shows what the page displayed and where you clicked and scrolled. Page text, including discussion posts, is recorded; your
          name and email are masked, form inputs are masked, and videos are not recorded.
        </li>
        <li>
          <strong>Errors, logs and traces.</strong> These record what happened on a page or request, such as a failed video load or a
          purchase being applied, plus your browser and device details.
        </li>
        <li>
          <strong>Tutor conversations.</strong> Every tutor chat, and every &quot;Ask AI&quot; answer, is traced in Sentry with its messages
          and answers.
        </li>
        <li>
          <strong>What we leave out.</strong> We don&apos;t send Sentry your cookies, request bodies, or web addresses&apos; query strings,
          and we remove the signatures from video links. Events are tagged with your account ID, never your name or email.
        </li>
      </ul>

      <h2>6. The AI tutor</h2>
      <p>
        When you use the tutor, your messages go to OpenAI along with the lesson&apos;s notes and the course outline, which in the chat
        shows which lessons you&apos;ve completed. &quot;Ask AI&quot; sends the question&apos;s text and lesson material, but no progress.
      </p>
      <p>
        We don&apos;t save tutor chats to your account; reloading the page starts a new one. Answers requested with &quot;Ask AI&quot; are
        saved and shown publicly under the question.
      </p>
      <p>Don&apos;t put personal data or secrets in tutor messages.</p>

      <h2>7. Cookies</h2>
      <p>
        We use only the cookies needed to keep you signed in, set by our sign-in system. We don&apos;t use advertising or analytics
        cookies.
      </p>

      <h2>8. How long we keep it</h2>
      <LegalTable
        head={["Data", "Kept until"]}
        rows={[
          ["Account, progress, discussion posts, AI answer counts", "You delete your account"],
          ["Purchase and subscription records", "[7 years], for tax and accounting, even after account deletion"],
          ["Sentry data (replays, errors, logs, traces)", "[30-90 days], under our Sentry plan"],
          ["Data held by Polar, OpenAI and other providers", "Their own retention policies"],
        ]}
      />
      <p>Deleting your account also deletes every reply under your questions, including other people&apos;s replies.</p>

      <h2>9. Security</h2>
      <ul>
        <li>Course videos are private and reachable only through links that expire.</li>
        <li>Sign-in uses Google or GitHub, so we never hold a password for you.</li>
        <li>Payments happen on Polar&apos;s checkout; card details never reach us.</li>
        <li>Administrator access is limited to verified email addresses we list.</li>
        <li>Payment events are accepted only with a valid signature from Polar.</li>
      </ul>
      <p>No system is perfectly secure, and we can&apos;t guarantee the security of data sent to us.</p>

      <h2>10. International transfers</h2>
      <p>
        Our providers may process data outside your country, including in the United States. Sentry stores our monitoring data in the EU.
        [Where required, transfers rely on the providers&apos; Standard Contractual Clauses or equivalent safeguards.]
      </p>

      <h2>11. Your rights and choices</h2>
      <p>
        Depending on where you live, you may have the right to access, correct, delete or export your personal data, to object to or
        restrict some processing, and to complain to a data protection authority.
      </p>
      <p>How to use them today:</p>
      <ul>
        <li>
          <strong>Delete your account</strong> or <strong>get a copy of your data:</strong> email [PRIVACY EMAIL] from your account&apos;s
          email address. There is no self-serve option yet; we&apos;ll respond within [30] days.
        </li>
        <li>
          <strong>Your name and picture</strong> come from your Google or GitHub account.
        </li>
        <li>
          <strong>Discussion posts</strong> can&apos;t be edited or deleted by you in the app yet; email us to remove one.
        </li>
        <li>
          <strong>Billing data:</strong> view receipts and cancel Monthly in Billing, Polar&apos;s customer portal.
        </li>
        <li>
          <strong>Signing out</strong> ends your session on that device.
        </li>
      </ul>

      <h2>12. Children</h2>
      <p>
        Lumen is not meant for children under [16], and we don&apos;t knowingly collect their data. If you believe a child has an account,
        email [PRIVACY EMAIL] and we&apos;ll delete it.
      </p>

      <h2>13. Changes and contact</h2>
      <p>We&apos;ll post any update here with a new effective date, and announce material changes [on the site and by email].</p>
      <p>
        Questions or requests: [LEGAL ENTITY NAME], [REGISTERED ADDRESS], [PRIVACY EMAIL].
      </p>
    </LegalPage>
  )
}
